# Site settings
title: mz
baseurl: ""
url: "https://syaning.github.io"

# Build settings
kramdown:
  input: GFM
permalink: pretty

# Third-party services
# just leave blank to disable it
google_analytics: 
